### ISSUE TITLE
Dynamic Linking QT causes images to not not load

### ISSUE THREAD

**Issue by GH-Rake** [multikill/GH_Injector_MSVC_2019_QT_5_15_0#3]
Dynamic Linking QT causes images to not not load

If you run the static linked build the images load fine

**Comment by multikill** [comment]
In the debug variant it is logical, here it is hidden. 
#ifdef _DEBUG
	lbl_hide_banner = 1;
#endif _DEBUG

In the release version it should be shown by default. But this could be set by the flag in the config.
**HIDEBANNER=false**

**Comment by multikill** [comment]
I tried i lote but nothing really helps.

i think there is something very strange happening when dynmaic linking with qtcore.dll
https://streamable.com/y8lt1f

**Comment by multikill** [comment]
solved the "...\plugins\imageformats\qjpeg.dll" was missing
